import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
// import Header from '@/components/Header'
// import Footer from '@/components/Footer'
// import ErrorWrapper from './error-wrapper'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: {
    default: 'Мое приложение на Next.js',
    template: '%s | Мое приложение на Next.js'
  },
  description: 'Я изучаю Next.js последней версии'
}

// export const metadata: Metadata = {
//   title: 'Новое приложение',
//   description: 'Generated by create next app'
// }

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Header />
        <ErrorWrapper>{children}</ErrorWrapper>
        <Footer /> */}
        <header className="bg-blue-300 ">
          <div className="ml-12">Шапка сайта</div>
        </header>
        <main className="flex-grow">{children}</main>
        <footer className="bg-gray-400">
          <div className="ml-12">Подвал сайта</div>
        </footer>
      </body>
    </html>
  )
}
